### ISSUE TITLE
Remove hyperlink to https://www.vgleadsheets.com

### ISSUE THREAD

**Issue by HSFlik** [sigmabeta/xiv-real-book#1]
As of 6/21/2022, all the sheets except for the ones listed below have `https://www.vgleadsheets.com` in the footer rather than `XIV Real Book` or similar.  Please remove references to https://www.vgleadsheets.com.

Final Fantasy XIV Shadowbringers - Tomorrow and Tomorrow
Final Fantasy XIV Shadowbringers - What Angel Wakes Me
Final Fantasy XIV Stormblood - eScape

**Comment by sigmabeta** [comment]
Fixed, thanks for the report!
